from __future__ import annotations

from pathlib import Path
from typing import Protocol, Sequence


class AndroidDriver(Protocol):
    """The read-only interaction boundary that an Appium driver can later implement."""

    def ensure_ready(self) -> None: ...

    def launch_instagram(self) -> None: ...

    def dump_ui(self) -> str: ...

    def tap_text(self, labels: Sequence[str], *, ui_xml: str | None = None) -> bool: ...

    def tap_resource_id(self, markers: Sequence[str], *, ui_xml: str | None = None) -> bool: ...

    def input_text(self, value: str) -> None: ...

    def swipe_up(self) -> None: ...

    def press_back(self) -> None: ...

    def open_instagram_url(self, url: str) -> None: ...

    def read_clipboard(self) -> str: ...

    def capture_screenshot(self, path: Path) -> None: ...
